name: Build Android App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      applicationId:
        description: 'Android Application ID'
        required: true
        default: 'com.companyname.clickme'
      versionName:
        description: 'Application Version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'
      buildNumber:
        description: 'Build Number (must be an integer)'
        required: true
        default: '1'
        type: string

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    - name: Install MAUI Workloads
      run: |
        dotnet workload install maui
        dotnet workload install android
        
    - name: Restore Dependencies
      run: dotnet restore ClickMe.sln
      
    - name: Build Android App
      run: >
        dotnet publish ClickMe.sln -c Release -f net8.0-android 
        /p:ApplicationId=${{ github.event.inputs.applicationId || 'com.companyname.clickme' }}
        /p:ApplicationDisplayVersion=${{ github.event.inputs.versionName || '1.0.0' }}
        /p:ApplicationVersion=${{ github.event.inputs.buildNumber || '1' }}
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: |
          **/*.apk
