name: Build Android App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        
    - name: Install MAUI Workloads
      run: |
        dotnet workload install maui
        dotnet workload install android
        
    - name: Restore Dependencies
      run: dotnet restore ClickMe.sln
      
    - name: Build Android App
      run: dotnet publish ClickMe.sln -c Release -f net8.0-android
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: ClickMe/bin/Release/net8.0-android/*/ClickMe.apk
